theme: jekyll-theme-cayman
title: Bingchuan Tian
google_analytics: UA-165426054-1

params:
  footer:
  katex: true
  header_heading_color: "#ff"
  header_background_color: "#159957"
  header_background_color_secondary: "#155799"
  
