theme: jekyll-theme-cayman
title: Bingchuan Tian
google_analytics: UA-165426054-1
params:
  header_heading_color: "#fff"
  header_background_color: "#00ffff"
  header_background_color_secondary: "#ff0000"
